#!/usr/bin/env bash

find_me() {
    # Find where we are installed through possible system links
    local SOURCE="${BASH_SOURCE[0]}"
    # resolve $SOURCE until the file is no longer a symlink
    while [ -h "${SOURCE}" ]; do
        PATH_BASE="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
        SOURCE="$(readlink "${SOURCE}")"
        # if SOURCE was a relative symlink, we need to resolve it
        # relative to the path where the symlink file was located
        [[ ${SOURCE} != /* ]] && SOURCE="${PATH_BASE}/${SOURCE}"
    done
    PATH_BASE="$(cd -P "$(dirname "${SOURCE}")" && pwd)"

    if [ -z "${PATH_BASE}" ] || [ ! -d "${PATH_BASE}" ]; then
        echo "Unable to determine script entry point: ${PATH_BASE}"
        return 1
    fi
    return 0
}

doc_title() {
    local LINE=""
    tput setaf 4
    tput bold
    while read -r LINE; do
        echo "${LINE}"
    done;
    tput sgr0
    return 0
}

movies_title() {
    doc_title <<'EOF'
                                                _
     ________  _  __      ____ ___  ____ _   __(_)__  _____
    / ___/ _ \| |/_/_____/ __ `__ \/ __ \ | / / / _ \/ ___/
   / /  /  __/>  </_____/ / / / / / /_/ / |/ / /  __(__  )
  /_/   \___/_/|_|     /_/ /_/ /_/\____/|___/_/\___/____/

EOF
    return 0
}

run_laravel_docker() {
    find_me || return 1
    movies_title

    local LARAVEL_ENV="${PATH_BASE}/.env"
    if [ ! -f "${LARAVEL_ENV}" ]; then
        cp "${LARAVEL_ENV}.example" "${LARAVEL_ENV}" || return 1
        echo "Copying .env.example"
    fi

    # export all variables in .env for use in docker-compose.yml
    set -o allexport
    source "${PATH_BASE}/.env"
    set +o allexport

    # options not set in .env
    if [ -z "${WEB_PORT}" ]; then
        export WEB_PORT="80"
    fi
    export PATH_BASE="${PATH_BASE}"

    if [ "${1}" = "test" ]; then
        local PREFIX=""
        which winpty > /dev/null 2>&1
        if [ "${?}" -eq 0 ]; then
            PREFIX="winpty"
        fi
        ${PREFIX} docker exec -it "${APP_NAME}_test" php artisan migrate:refresh --seed
        ${PREFIX} docker exec -it "${APP_NAME}_test" vendor/bin/phpunit
        exit 0
    else
        cd "${PATH_BASE}/docker"
        docker-compose "$@"
    fi
    local RESULT="${?}"
    echo
    return "${RESULT}"
}

IFS=$'\n'
run_laravel_docker "$@"
exit "${?}"
